service: ProductService

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  environment:
    POSTGRESQL_CONNECTION_STR: ${env:POSTGRESQL_CONNECTION_STR}
  httpApi:
    cors: true

functions:
  createProduct:
    handler: createProduct.handler
    events:
      - httpApi:
          path: /products
          method: POST
  getProductsList:
    handler: getProductsList.handler
    events:
      - httpApi:
          path: /products
          method: GET
  getProductsById:
    handler: getProductsById.handler
    events:
     - httpApi:
        path: /products/{productId}
        method: GET
useDotenv: true